export const fixtures = {
    applySettings: [
        {
            description: 'language param invalid type',
            params: { language: 1 },
            error: 'Parameter "language" has invalid type. "string" expected.',
        },
        {
            description: 'success',
            params: { language: 'en' },
        },
    ],
    applyFlags: [
        {
            description: 'missing flags param',
            params: { foo: 1 },
            error: 'Parameter "flags" is missing.',
        },
        {
            description: 'flags param invalid type',
            params: { flags: '1' },
            error: 'Parameter "flags" has invalid type. "number" expected.',
        },
        {
            description: 'success',
            params: { flags: 1 },
        },
    ],
    backupDevice: [],
    binanceGetAddress: [],
    binanceGetPublicKey: [],
    binanceSignTransaction: [],
    blockchainDisconnect: [],
    blockchainEstimateFee: [],
    blockchainGetAccountBalanceHistory: [],
    blockchainGetCurrentFiatRates: [],
    blockchainGetFiatRatesForTimestamps: [],
    blockchainGetTransactions: [],
    blockchainSetCustomBackend: [],
    blockchainSubscribe: [],
    blockchainSubscribeFiatRates: [],
    blockchainUnsubscribe: [],
    blockchainUnsubscribeFiatRates: [],
    cardanoGetAddress: [],
    cardanoGetPublicKey: [],
    cardanoSignTransaction: [],
    changePin: [],
    cipherKeyValue: [],
    composeTransaction: [],
    customMessage: [],
    debugLinkDecision: [],
    debugLinkGetState: [],
    eosGetPublicKey: [],
    eosSignTransaction: [],
    ethereumGetAddress: [],
    ethereumGetPublicKey: [],
    ethereumSignMessage: [],
    ethereumSignTransaction: [],
    ethereumVerifyMessage: [],
    firmwareUpdate: [],
    getAccountInfo: [],
    getAddress: [],
    getCoinInfo: [],
    getDeviceState: [],
    getFeatures: [],
    getPublicKey: [],
    getSettings: [],
    liskGetAddress: [],
    liskGetPublicKey: [],
    liskSignMessage: [],
    liskSignTransaction: [],
    liskVerifyMessage: [],
    loadDevice: [],
    nemGetAddress: [],
    nemSignTransaction: [],
    pushTransaction: [],
    recoveryDevice: [],
    requestLogin: [],
    resetDevice: [],
    rippleGetAddress: [],
    rippleSignTransaction: [],
    signMessage: [],
    signTransaction: [],
    stellarGetAddress: [],
    stellarSignTransaction: [],
    tezosGetAddress: [],
    tezosGetPublicKey: [],
    tezosSignTransaction: [],
    verifyMessage: [],
    wipeDevice: [],
};
