/* @flow */

export const CORE_EVENT: 'CORE_EVENT' = 'CORE_EVENT';
export const UI_EVENT: 'UI_EVENT' = 'UI_EVENT';
export const DEVICE_EVENT: 'DEVICE_EVENT' = 'DEVICE_EVENT';
export const TRANSPORT_EVENT: 'TRANSPORT_EVENT' = 'TRANSPORT_EVENT';
export const RESPONSE_EVENT: 'RESPONSE_EVENT' = 'RESPONSE_EVENT';
export const BLOCKCHAIN_EVENT: 'BLOCKCHAIN_EVENT' = 'BLOCKCHAIN_EVENT';
