export default {
    method: 'getFeatures',
    setup: {
        mnemonic: 'mnemonic_12',
    },
    tests: [
        {
            description: "get features",
            params: {},
            result: {
                vendor: 'trezor.io',
                major_version: 2,
                minor_version: 3,
                patch_version: 1,
                bootloader_mode: null,
                pin_protection: false,
                passphrase_protection: false,
                language: 'en-US',
                label: 'TrezorT',
                initialized: true,
                revision: '33303430663136',
                bootloader_hash: null,
                imported: null,
                pin_cached: false,
                firmware_present: null,
                needs_backup: false,
                flags: 0,
                model: 'T',
                fw_major: null,
                fw_minor: null,
                fw_patch: null,
                fw_vendor: null,
                fw_vendor_keys: null,
                unfinished_backup: false,
                no_backup: false,
                recovery_mode: false,
                capabilities: [
                  'Capability_Bitcoin',
                  'Capability_Bitcoin_like',
                  'Capability_Binance',
                  'Capability_Cardano',
                  'Capability_Crypto',
                  'Capability_EOS',
                  'Capability_Ethereum',
                  'Capability_Lisk',
                  'Capability_Monero',
                  'Capability_NEM',
                  'Capability_Ripple',
                  'Capability_Stellar',
                  'Capability_Tezos',
                  'Capability_U2F',
                  'Capability_Shamir',
                  'Capability_ShamirGroups',
                  'Capability_PassphraseEntry'
                ],
                backup_type: 'Bip39',
                sd_card_present: true,
                sd_protection: false,
                wipe_code_protection: false,
                session_id: '4a0d361a211cb3660c87f58ffb96e18f1ea08e2be50867e900a592025f549fe8',
                passphrase_always_on_device: false
            }
        },
    ],
};
