name: Test api karma

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
    - run: yarn build
    - run: yarn build:inline
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build
        if-no-files-found: error
        retention-days: 1

  initialization:
    needs: setup
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Retrieve artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build
    # xvfb is required to run karma 
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum ./tests/run.sh -s 'yarn test:karma:production init'
